* Kmer_Counter.py: A Comprehensive Guide 
** Visualizations
   Kmer_counter is a python command line tool within the krepe package that
   allows bioinformaticists to count the kmers with a .fasta, .fna, or .fastq
   file and lets the user create bar graphs that represent all of the kmers 
   at length k present in a file along with their abundance. It also provides
   a simple uncompressed De Bruijn graph that is ideal for smaller values of
   k and is a nice visualization of the genome.
** Execution
   After making the script executable using chmod +x you can run the
   program with:
   $ ./$PATH/Kmer_counter.py (desired k-mer length) (file name) (bar graph?) (de bruijn graph?)
   Or using python3:
   $ python3 $PATH/Kmer_counter.py (desired k-mer length) (file name) (bar graph?) (de bruijn graph?)
** Tutorial
   Navigate to the tests folder and retrieve the Tuberculosis.fna file.
   Kmer_Counter.py has two bar graph options: plot_distribution, and
   not_plot_distribution. The De Bruijn graph also has two arguements:
   plot_de_bruijn and not_plot_de_bruijn.
   An example usage would be:
   $ python3 Kmer_counter.py 25 tuberculosis.fna plot_distribution not_plot_de_bruijn
 
