* Organism_comparison.py: A Comprehensive Guide

** Explanation:
   Organism_comparison.py allows the user to count kmers of a specified kmer 
   length and create a dictionary holding that kmer and its abundance. It 
   then allows the user to compare two DNA samples whether they both be .fna,
   .fasta, or .fastq. Once the k-mer dictionary of both files has been created,
   organism_comparison.py will calculate the jaccard similarity of the files. 
   This can be used to calculate the genetic diversity of the two organisms.
   Organism_comparison.py allows you to then create a venn diagram of the
   intersection of the kmer dictionaries.

** Execution:
   Organism_comparison.py is a one of KREPE's many python command line tools
   for bioinformaticists. Organism_comparison.py makes use of the powerful
   sourmash python library to make basic kmer analysis easier than ever.

   Make the program executable using chmod +x organism_comparison.py and run
   it like this: 
   $ organism_comparison.py (k-mer length) (file1, file2) (file type)
   or alternatively use python3 to run it: 
   $ python3 organism_comparison.py (k-mer length) (file1, file 2) (file type)

** Tutorial:
   $ PATH/organism_comparison 21 tuberculosis.fna streptococus.fna -fna
   $ python3 organism_comparison.py 21 tuberculosis.fna streptococus.fna -fna
